In [1]:
import numpy as np 
import pandas as pd

In [2]:
df_vocab = pd.read_csv("df_vocab.csv")

In [3]:
df_vocab

    Unnamed: 0        0      1       2     3  count
0            0     Back  15som  05Twis  FREE    220
1            1     Back  15som  15Twis  FREE    122
2            2     Back  15som  25Twis  FREE     59
3            3     Back  15som  NoTwis  PIKE    251
4            4     Back  15som  NoTwis  TUCK     40
5            5     Back  25som  15Twis  PIKE    509
6            6     Back  25som  25Twis  PIKE    184
7            7     Back  25som  NoTwis  PIKE    960
8            8     Back  25som  NoTwis  TUCK    410
9            9     Back   2som  15Twis  FREE    206
10          10     Back   2som  25Twis  FREE     74
11          11     Back  35som  NoTwis  PIKE    153
12          12     Back  35som  NoTwis  TUCK    453
13          13     Back   3som  NoTwis  PIKE     42
14          14     Back   3som  NoTwis  TUCK    115
15          15     Back   Dive  NoTwis  PIKE    668
16          16     Back   Dive  NoTwis  TUCK     58
17          17  Forward  15som   1Twis  FREE    335
18          18  Forward  15som   2Twis  FREE     69
19          19  Forward  15som  NoTwis  PIKE    611
20          20  Forward   1som  NoTwis  PIKE    115
21          21  Forward  25som   1Twis  PIKE    688
22          22  Forward  25som   2Twis  PIKE    403
23          23  Forward  25som   3Twis  PIKE     68
24          24  Forward  25som  NoTwis  PIKE    525
25          25  Forward  25som  NoTwis  TUCK     48
26          26  Forward  35som  NoTwis  PIKE   1159
27          27  Forward  35som  NoTwis  TUCK    256
28          28  Forward  45som  NoTwis  TUCK    361
29          29  Forward   Dive  NoTwis  PIKE    321
30          30  Forward   Dive  NoTwis   STR     40
31          31   Inward  15som  NoTwis  PIKE    755
32          32   Inward  15som  NoTwis  TUCK     64
33          33   Inward  25som  NoTwis  PIKE    622
34          34   Inward  25som  NoTwis  TUCK    595
35          35   Inward  35som  NoTwis  TUCK   1066
36          36   Inward   Dive  NoTwis  PIKE    304
37          37  Reverse  15som  05Twis  FREE     75
38          38  Reverse  15som  15Twis  FREE     84
39          39  Reverse  15som  25Twis  FREE     60
40          40  Reverse  15som  35Twis  FREE     54
41          41  Reverse  15som  NoTwis  PIKE    153
42          42  Reverse  25som  15Twis  PIKE    145
43          43  Reverse  25som  NoTwis  PIKE    451
44          44  Reverse  25som  NoTwis  TUCK    552
45          45  Reverse  35som  NoTwis  TUCK    591
46          46  Reverse   Dive  NoTwis  PIKE    792
47          47  Reverse   Dive  NoTwis  TUCK     57

In [6]:
df_vocab["1"].value_counts()

1
15som    15
25som    14
Dive      7
35som     6
2som      2
3som      2
1som      1
45som     1
Name: count, dtype: int64

In [8]:
df_vocab.groupby(["1"])["count"].sum()

1
15som    2952
1som      115
25som    6160
2som      280
35som    3678
3som      157
45som     361
Dive     2240
Name: count, dtype: int64

In [9]:
df_vocab["count"].sum()

np.int64(15943)

In [10]:
train = pd.read_csv("df_exsists.csv")

In [11]:
train

      Unnamed: 0           vid_name  label  start_frame  end_frame
0              0  3qq031609lA_00002      0            0        123
1              1  3qq031609lA_00004      0            0        102
2              2  5V-dKBtmKLI_00018      0            0         55
3              3  5V-dKBtmKLI_00085      0            0         80
4              4  5V-dKBtmKLI_00086      0            0         89
...          ...                ...    ...          ...        ...
7067        7067  mGRum47TLX0_00040     47            0         56
7068        7068  mGRum47TLX0_00044     47            0        112
7069        7069  ovWCmIMMkRI_00050     47            0        108
7070        7070  ovWCmIMMkRI_00051     47            0        125
7071        7071  ovWCmIMMkRI_00052     47            0         91

[7072 rows x 5 columns]

In [20]:
test = pd.read_csv("/Users/mrinalraj/Downloads/WebDownload/Driving48/ProcessedTestCorrect.csv")

In [21]:
test

      Unnamed: 0           vid_name  label  start_frame  end_frame
0             44  MbzIpx8kAD0_00036      0            0        192
1             58  bl0C6d9QgIg_00018      0            0        331
2             70  zmacW6f2Tdk_00024      0            0        182
3            119  zmacW6f2Tdk_00050      1            0        184
4            142  cs8g1es4vfM_00004      3            0        269
...          ...                ...    ...          ...        ...
3332       16957  D8YKHC5hmUs_00069     47            0        192
3333       16972  Y7QZcr24ye0_00700     47            0        231
3334       16990  sk8TafuB3lU_00223     47            0        304
3335       16992  xbQCwTHcGN8_00310     47            0        199
3336       16994  zYHstCxnAPA_00108     47            0        253

[3337 rows x 5 columns]

In [12]:
df_vocab["label"] = df_vocab.index

In [13]:
df_vocab

    Unnamed: 0        0      1       2     3  count  label
0            0     Back  15som  05Twis  FREE    220      0
1            1     Back  15som  15Twis  FREE    122      1
2            2     Back  15som  25Twis  FREE     59      2
3            3     Back  15som  NoTwis  PIKE    251      3
4            4     Back  15som  NoTwis  TUCK     40      4
5            5     Back  25som  15Twis  PIKE    509      5
6            6     Back  25som  25Twis  PIKE    184      6
7            7     Back  25som  NoTwis  PIKE    960      7
8            8     Back  25som  NoTwis  TUCK    410      8
9            9     Back   2som  15Twis  FREE    206      9
10          10     Back   2som  25Twis  FREE     74     10
11          11     Back  35som  NoTwis  PIKE    153     11
12          12     Back  35som  NoTwis  TUCK    453     12
13          13     Back   3som  NoTwis  PIKE     42     13
14          14     Back   3som  NoTwis  TUCK    115     14
15          15     Back   Dive  NoTwis  PIKE    668     15
16          16     Back   Dive  NoTwis  TUCK     58     16
17          17  Forward  15som   1Twis  FREE    335     17
18          18  Forward  15som   2Twis  FREE     69     18
19          19  Forward  15som  NoTwis  PIKE    611     19
20          20  Forward   1som  NoTwis  PIKE    115     20
21          21  Forward  25som   1Twis  PIKE    688     21
22          22  Forward  25som   2Twis  PIKE    403     22
23          23  Forward  25som   3Twis  PIKE     68     23
24          24  Forward  25som  NoTwis  PIKE    525     24
25          25  Forward  25som  NoTwis  TUCK     48     25
26          26  Forward  35som  NoTwis  PIKE   1159     26
27          27  Forward  35som  NoTwis  TUCK    256     27
28          28  Forward  45som  NoTwis  TUCK    361     28
29          29  Forward   Dive  NoTwis  PIKE    321     29
30          30  Forward   Dive  NoTwis   STR     40     30
31          31   Inward  15som  NoTwis  PIKE    755     31
32          32   Inward  15som  NoTwis  TUCK     64     32
33          33   Inward  25som  NoTwis  PIKE    622     33
34          34   Inward  25som  NoTwis  TUCK    595     34
35          35   Inward  35som  NoTwis  TUCK   1066     35
36          36   Inward   Dive  NoTwis  PIKE    304     36
37          37  Reverse  15som  05Twis  FREE     75     37
38          38  Reverse  15som  15Twis  FREE     84     38
39          39  Reverse  15som  25Twis  FREE     60     39
40          40  Reverse  15som  35Twis  FREE     54     40
41          41  Reverse  15som  NoTwis  PIKE    153     41
42          42  Reverse  25som  15Twis  PIKE    145     42
43          43  Reverse  25som  NoTwis  PIKE    451     43
44          44  Reverse  25som  NoTwis  TUCK    552     44
45          45  Reverse  35som  NoTwis  TUCK    591     45
46          46  Reverse   Dive  NoTwis  PIKE    792     46
47          47  Reverse   Dive  NoTwis  TUCK     57     47

In [15]:
df_merged = train.merge(df_vocab[["label", "1"]], on="label", how="left")

In [22]:
df_merged_test = test.merge(df_vocab[["label", "1"]], on="label", how="left")
df_merged_test

      Unnamed: 0           vid_name  label  start_frame  end_frame      1
0             44  MbzIpx8kAD0_00036      0            0        192  15som
1             58  bl0C6d9QgIg_00018      0            0        331  15som
2             70  zmacW6f2Tdk_00024      0            0        182  15som
3            119  zmacW6f2Tdk_00050      1            0        184  15som
4            142  cs8g1es4vfM_00004      3            0        269  15som
...          ...                ...    ...          ...        ...    ...
3332       16957  D8YKHC5hmUs_00069     47            0        192   Dive
3333       16972  Y7QZcr24ye0_00700     47            0        231   Dive
3334       16990  sk8TafuB3lU_00223     47            0        304   Dive
3335       16992  xbQCwTHcGN8_00310     47            0        199   Dive
3336       16994  zYHstCxnAPA_00108     47            0        253   Dive

[3337 rows x 6 columns]

In [16]:
df_merged

      Unnamed: 0           vid_name  label  start_frame  end_frame      1
0              0  3qq031609lA_00002      0            0        123  15som
1              1  3qq031609lA_00004      0            0        102  15som
2              2  5V-dKBtmKLI_00018      0            0         55  15som
3              3  5V-dKBtmKLI_00085      0            0         80  15som
4              4  5V-dKBtmKLI_00086      0            0         89  15som
...          ...                ...    ...          ...        ...    ...
7067        7067  mGRum47TLX0_00040     47            0         56   Dive
7068        7068  mGRum47TLX0_00044     47            0        112   Dive
7069        7069  ovWCmIMMkRI_00050     47            0        108   Dive
7070        7070  ovWCmIMMkRI_00051     47            0        125   Dive
7071        7071  ovWCmIMMkRI_00052     47            0         91   Dive

[7072 rows x 6 columns]

In [17]:
df_merged = df_merged.rename(columns={"som": "label_som"})

In [18]:
df_merged.to_csv("df_exists_with_som.csv", index=False)

print(df_merged.head())

   Unnamed: 0           vid_name  label  start_frame  end_frame      1
0           0  3qq031609lA_00002      0            0        123  15som
1           1  3qq031609lA_00004      0            0        102  15som
2           2  5V-dKBtmKLI_00018      0            0         55  15som
3           3  5V-dKBtmKLI_00085      0            0         80  15som
4           4  5V-dKBtmKLI_00086      0            0         89  15som

In [23]:
df_merged_test = df_merged_test.rename(columns={"som": "label_som"})

In [24]:
df_merged_test

      Unnamed: 0           vid_name  label  start_frame  end_frame      1
0             44  MbzIpx8kAD0_00036      0            0        192  15som
1             58  bl0C6d9QgIg_00018      0            0        331  15som
2             70  zmacW6f2Tdk_00024      0            0        182  15som
3            119  zmacW6f2Tdk_00050      1            0        184  15som
4            142  cs8g1es4vfM_00004      3            0        269  15som
...          ...                ...    ...          ...        ...    ...
3332       16957  D8YKHC5hmUs_00069     47            0        192   Dive
3333       16972  Y7QZcr24ye0_00700     47            0        231   Dive
3334       16990  sk8TafuB3lU_00223     47            0        304   Dive
3335       16992  xbQCwTHcGN8_00310     47            0        199   Dive
3336       16994  zYHstCxnAPA_00108     47            0        253   Dive

[3337 rows x 6 columns]

In [25]:
df_merged_test.to_csv("df_exists_with_som_test.csv", index=False)
print(df_merged_test.head())

   Unnamed: 0           vid_name  label  start_frame  end_frame      1
0          44  MbzIpx8kAD0_00036      0            0        192  15som
1          58  bl0C6d9QgIg_00018      0            0        331  15som
2          70  zmacW6f2Tdk_00024      0            0        182  15som
3         119  zmacW6f2Tdk_00050      1            0        184  15som
4         142  cs8g1es4vfM_00004      3            0        269  15som

In [27]:
df_merged_test

      Unnamed: 0           vid_name  label  start_frame  end_frame      1
0             44  MbzIpx8kAD0_00036      0            0        192  15som
1             58  bl0C6d9QgIg_00018      0            0        331  15som
2             70  zmacW6f2Tdk_00024      0            0        182  15som
3            119  zmacW6f2Tdk_00050      1            0        184  15som
4            142  cs8g1es4vfM_00004      3            0        269  15som
...          ...                ...    ...          ...        ...    ...
3332       16957  D8YKHC5hmUs_00069     47            0        192   Dive
3333       16972  Y7QZcr24ye0_00700     47            0        231   Dive
3334       16990  sk8TafuB3lU_00223     47            0        304   Dive
3335       16992  xbQCwTHcGN8_00310     47            0        199   Dive
3336       16994  zYHstCxnAPA_00108     47            0        253   Dive

[3337 rows x 6 columns]

In [28]:
df_merged["1"].value_counts(), df_merged_test["1"].value_counts()

(1
 25som    2825
 35som    1681
 15som    1222
 Dive     1015
 45som     174
 2som       75
 3som       48
 1som       32
 Name: count, dtype: int64,
 1
 25som    1273
 15som     722
 35som     647
 Dive      576
 45som      63
 2som       29
 3som       18
 1som        9
 Name: count, dtype: int64)

In [30]:
unique_soms = sorted(df_merged["1"].unique())
som2idx = {som: idx for idx, som in enumerate(unique_soms)}
idx2som = {idx: som for som, idx in som2idx.items()}
som2idx, idx2som

({'15som': 0,
  '1som': 1,
  '25som': 2,
  '2som': 3,
  '35som': 4,
  '3som': 5,
  '45som': 6,
  'Dive': 7},
 {0: '15som',
  1: '1som',
  2: '25som',
  3: '2som',
  4: '35som',
  5: '3som',
  6: '45som',
  7: 'Dive'})

In [1]:
import pandas as pd
abc = pd.read_csv("df_exsists.csv")
abc["label"].value_counts()

label
7     494
35    486
26    468
46    340
45    337
33    293
15    283
34    280
21    279
31    264
43    217
22    212
19    212
12    210
24    204
44    202
8     200
5     192
36    183
28    174
0     146
3     115
29    102
6     101
27    100
17     90
11     80
42     76
1      74
32     71
47     55
41     54
16     52
9      49
4      44
25     42
18     33
14     33
23     33
20     32
40     31
37     30
10     26
38     22
39     20
2      16
13     15
Name: count, dtype: int64