In [1]:
import os
import json
import pandas as pd
from collections import Counter

# Paths
base_path = '.'  # Replace with your actual path
rgb_path = os.path.join(base_path, 'rgb')
train_json = os.path.join(base_path, 'Diving48_V2_train.json')
test_json = os.path.join(base_path, 'Diving48_V2_test.json')
vocab_json = os.path.join(base_path, 'Diving48_vocab.json')

# Load JSONs
with open(train_json, 'r') as f:
    train_data = json.load(f)

with open(test_json, 'r') as f:
    test_data = json.load(f)

with open(vocab_json, 'r') as f:
    vocab_data = json.load(f)

# Convert to DataFrame for easy handling
df_train = pd.DataFrame(train_data)
df_test = pd.DataFrame(test_data)

# Show head
print("Train Data Head:")
print(df_train.head())

print("\nTest Data Head:")
print(df_test.head())

# Count unique classes
train_classes = df_train['label'].unique()
test_classes = df_test['label'].unique()
print(f"\nUnique Classes in Train: {len(train_classes)}")
print(f"Unique Classes in Test: {len(test_classes)}")

# Class distribution
print("\nTrain Class Distribution:")
print(df_train['label'].value_counts())

print("\nTest Class Distribution:")
print(df_test['label'].value_counts())

# Check total MP4 files in RGB folder
mp4_files = [f for f in os.listdir(rgb_path) if f.endswith('.mp4')]
print(f"\nTotal video files in rgb/: {len(mp4_files)}")

Train Data Head:
            vid_name  label  start_frame  end_frame
0  -mmq0PT-u8k_00155      0            0         48
1  -mmq0PT-u8k_00156      0            0         70
2  -mmq0PT-u8k_00157      0            0         90
3  3qq031609lA_00002      0            0        123
4  3qq031609lA_00004      0            0        102

Test Data Head:
            vid_name  label  start_frame  end_frame
0  8qRmKunCjtY_00016      0            0         78
1  CVAfPfVFulQ_00038      0            0        100
2  CVAfPfVFulQ_00040      0            0         79
3  CVAfPfVFulQ_00048      0            0         76
4  CVAfPfVFulQ_00049      0            0         83

Unique Classes in Train: 47
Unique Classes in Test: 47

Train Class Distribution:
label
26    1053
35     992
7      901
46     816
21     689
31     683
19     604
15     591
34     571
33     568
45     559
44     518
24     484
5      467
8      424
12     421
43     406
22     355
17     349
36     346
28     326
3      259
27     250
29     231
0      222
9      212
41     160
6      160
20     148
11     144
42     130
1      109
14     102
38      91
10      74
37      69
18      68
32      61
23      57
2       49
40      48
16      48
25      46
39      45
13      44
47      44
4       33
Name: count, dtype: int64

Test Class Distribution:
label
46    163
15    133
19    117
34     99
35     95
31     88
36     81
24     80
0      73
26     69
44     67
7      63
45     57
8      54
21     52
22     52
28     51
1      47
32     43
5      41
16     39
27     39
33     39
47     32
20     31
3      31
12     28
4      21
6      21
17     21
29     20
11     17
25     16
10     15
18     14
13     12
41     10
43      9
23      7
39      5
37      4
42      3
2       3
40      2
38      2
9       2
14      2
Name: count, dtype: int64

Total video files in rgb/: 18404

In [2]:
import os
import pandas as pd


# Concatenate test and rtrain
df_all = pd.concat([df_test, df_train], ignore_index=True)
df_all.to_csv("df_all.csv")
# # === Step 2: Process filenames from folder ===
# video_folder = "TestAnnotated/"  # change this to your folder path
# video_files = os.listdir(video_folder)

# # Remove prefix and suffix to get cleaned video names
# cleaned_names = set()
# for file in video_files:
#     if file.endswith(".mp4") and file.startswith("queries_"):
#         clean_name = file.replace("queries_", "").replace(".mp4", "")
#         cleaned_names.add(clean_name)

In [3]:
df_train[df_train["label"]==30]

Empty DataFrame
Columns: [vid_name, label, start_frame, end_frame]
Index: []

In [4]:
# 
df_test_exist = df_all[df_all['vid_name'].isin(cleaned_names)]

# === Step 4: Show count of each class ===
class_counts = df_test_exist['label'].value_counts()

# Output
print("Filtered test DataFrame shape:", df_test_exist.shape)
print("Class distribution in filtered test set:")
print(class_counts)

Filtered test DataFrame shape: (2087, 4)
Class distribution in filtered test set:
label
46    157
26    129
15    113
44    111
19    109
21    103
31     98
34     95
7      94
24     84
8      82
5      77
17     75
35     71
12     58
36     49
45     48
3      48
33     48
27     44
0      37
22     34
28     34
43     31
29     29
38     25
1      20
41     20
11     19
6      18
14     13
9      13
18     10
32     10
42      9
37      8
10      8
20      8
39      8
25      8
23      7
16      7
40      5
2       4
4       4
47      3
13      2
Name: count, dtype: int64

In [6]:
df_test_exist['label'].value_counts().index.shape

(47,)

In [8]:
df_all["vid_name"].nunique()

16997

In [10]:
NOTProcessed = pd.read_csv("TestProsessing.csv")
NOTProcessed

                 Names
0    _lmT4WlK7G0_00017
1    _tigfCJFLZg_00097
2    _tigfCJFLZg_00165
3    _tigfCJFLZg_00196
4    _tigfCJFLZg_00198
..                 ...
496  zYHstCxnAPA_00829
497  zYHstCxnAPA_00833
498  zYHstCxnAPA_00835
499  zYHstCxnAPA_00838
500  zYHstCxnAPA_00842

[501 rows x 1 columns]

In [14]:
mask = df_test_exist["vid_name"].isin(NOTProcessed["Names"])
df_test_exist = df_test_exist[mask == False]

In [15]:
df_test_exist.to_csv("ProcessedTestCorrect.csv")

In [19]:
df_test_exist[df_test_exist["label"]==30]

Empty DataFrame
Columns: [vid_name, label, start_frame, end_frame]
Index: []

In [16]:
df_test_exist["label"].value_counts()

label
46    126
26    111
44     88
15     86
19     81
7      80
21     79
34     74
31     72
5      68
24     65
8      60
35     58
12     51
17     51
45     44
33     39
36     34
28     33
3      30
0      28
27     27
22     27
43     23
38     18
29     17
11     16
6      16
1      14
41     10
14     10
18      9
9       8
42      7
25      7
32      7
23      6
20      6
10      6
37      6
39      6
40      5
16      4
2       3
4       3
13      2
47      2
Name: count, dtype: int64

In [18]:
len(df_test_exist["label"].value_counts().index)

47

In [24]:
for i in range(50):
    if i not in df_test_exist["label"].value_counts().index:
        print(i)

30
48
49

In [33]:
def check_file_exists(vid_name):
    filename = f"{vid_name}_tracking.pt"
    return os.path.exists(os.path.join("Test", filename))

In [34]:
df_test_exist['exists'] = df_test_exist['vid_name'].apply(check_file_exists)
print(df_test_exist['exists'].value_counts())

exists
True     1605
False      18
Name: count, dtype: int64

/var/folders/8g/y90dcmtn1t39t7rwgnkvjspm0000gn/T/ipykernel_3485/323512930.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_exist['exists'] = df_test_exist['vid_name'].apply(check_file_exists)

In [37]:
len(df_test_exist.loc[df_test_exist["exists"]==True, "label"].value_counts().index)

47

In [36]:
df_test_exist

                vid_name  label  start_frame  end_frame  exists
44     MbzIpx8kAD0_00036      0            0        192    True
70     zmacW6f2Tdk_00024      0            0        182    True
119    zmacW6f2Tdk_00050      1            0        184    True
142    cs8g1es4vfM_00004      3            0        269    True
144    jMEYIEYkpY0_00029      3            0        188    True
...                  ...    ...          ...        ...     ...
16933  zYHstCxnAPA_00511     46            0        279    True
16939  zYHstCxnAPA_00533     46            0        205    True
16941  zYHstCxnAPA_00538     46            0        299    True
16954  2x00lRzlTVQ_00039     47            0        199    True
16957  D8YKHC5hmUs_00069     47            0        192    True

[1623 rows x 5 columns]

In [41]:
df_test_exist[df_test_exist["exists"]==True].drop(columns="exists").to_csv("ProcessedTestCorrect.csv")

In [1]:
import os
import pandas as pd

In [6]:
FolderContent = os.listdir("Test/")

In [4]:
len(os.listdir("TestAnnotated/"))

4332

In [5]:
Test2 = pd.read_csv("NotTestProceesed22July.csv")
print(Test2)

                 Names
0    _8Vy3dlHg2w_00044
1    _lmT4WlK7G0_00099
2    _lmT4WlK7G0_00117
3    _tigfCJFLZg_00045
4    _tigfCJFLZg_00234
..                 ...
311  zYHstCxnAPA_00262
312  zYHstCxnAPA_00299
313  zYHstCxnAPA_00302
314  zYHstCxnAPA_00306
315  zYHstCxnAPA_00307

[316 rows x 1 columns]

In [7]:
cleaned_names = set()
for file in FolderContent:
    if file.endswith("_tracking.pt"):
        clean_name = file.replace("_tracking.pt", "")
        cleaned_names.add(clean_name)

In [11]:
Test2[Test2["Names"].isin(cleaned_names)]

                 Names
0    _8Vy3dlHg2w_00044
1    _lmT4WlK7G0_00099
2    _lmT4WlK7G0_00117
3    _tigfCJFLZg_00045
4    _tigfCJFLZg_00234
..                 ...
303  zYHstCxnAPA_00115
304  zYHstCxnAPA_00143
305  zYHstCxnAPA_00147
306  zYHstCxnAPA_00169
307  zYHstCxnAPA_00177

[308 rows x 1 columns]