In [59]:
import os
import json
import pandas as pd
from collections import Counter

# Paths
base_path = '.'  # Replace with your actual path
rgb_path = os.path.join(base_path, 'rgb')
train_json = os.path.join(base_path, 'Diving48_V2_train.json')
test_json = os.path.join(base_path, 'Diving48_V2_test.json')
vocab_json = os.path.join(base_path, 'Diving48_vocab.json')

# Load JSONs
with open(train_json, 'r') as f:
    train_data = json.load(f)

with open(test_json, 'r') as f:
    test_data = json.load(f)

with open(vocab_json, 'r') as f:
    vocab_data = json.load(f)

# Convert to DataFrame for easy handling
df_train = pd.DataFrame(train_data)
df_test = pd.DataFrame(test_data)

# Show head
print("Train Data Head:")
print(df_train.head())

print("\nTest Data Head:")
print(df_test.head())

# Count unique classes
train_classes = df_train['label'].unique()
test_classes = df_test['label'].unique()
print(f"\nUnique Classes in Train: {len(train_classes)}")
print(f"Unique Classes in Test: {len(test_classes)}")

# Class distribution
print("\nTrain Class Distribution:")
print(df_train['label'].value_counts())

print("\nTest Class Distribution:")
print(df_test['label'].value_counts())

# Check total MP4 files in RGB folder
mp4_files = [f for f in os.listdir(rgb_path) if f.endswith('.mp4')]
print(f"\nTotal video files in rgb/: {len(mp4_files)}")

Train Data Head:
            vid_name  label  start_frame  end_frame
0  -mmq0PT-u8k_00155      0            0         48
1  -mmq0PT-u8k_00156      0            0         70
2  -mmq0PT-u8k_00157      0            0         90
3  3qq031609lA_00002      0            0        123
4  3qq031609lA_00004      0            0        102

Test Data Head:
            vid_name  label  start_frame  end_frame
0  8qRmKunCjtY_00016      0            0         78
1  CVAfPfVFulQ_00038      0            0        100
2  CVAfPfVFulQ_00040      0            0         79
3  CVAfPfVFulQ_00048      0            0         76
4  CVAfPfVFulQ_00049      0            0         83

Unique Classes in Train: 47
Unique Classes in Test: 47

Train Class Distribution:
label
26    1053
35     992
7      901
46     816
21     689
31     683
19     604
15     591
34     571
33     568
45     559
44     518
24     484
5      467
8      424
12     421
43     406
22     355
17     349
36     346
28     326
3      259
27     250
29     231
0      222
9      212
41     160
6      160
20     148
11     144
42     130
1      109
14     102
38      91
10      74
37      69
18      68
32      61
23      57
2       49
40      48
16      48
25      46
39      45
13      44
47      44
4       33
Name: count, dtype: int64

Test Class Distribution:
label
46    163
15    133
19    117
34     99
35     95
31     88
36     81
24     80
0      73
26     69
44     67
7      63
45     57
8      54
21     52
22     52
28     51
1      47
32     43
5      41
16     39
27     39
33     39
47     32
20     31
3      31
12     28
4      21
6      21
17     21
29     20
11     17
25     16
10     15
18     14
13     12
41     10
43      9
23      7
39      5
37      4
42      3
2       3
40      2
38      2
9       2
14      2
Name: count, dtype: int64

Total video files in rgb/: 18404

In [60]:
df_train.shape, df_train["vid_name"].nunique()

((15027, 4), 15027)

In [61]:
df_train['vid_name'].value_counts(), df_test['vid_name'].value_counts()

(vid_name
 -mmq0PT-u8k_00155    1
 _lmT4WlK7G0_00123    1
 _lmT4WlK7G0_00058    1
 _lmT4WlK7G0_00059    1
 _lmT4WlK7G0_00060    1
                     ..
 nOlRwoxsDJ0_00027    1
 nOlRwoxsDJ0_00028    1
 nOlRwoxsDJ0_00029    1
 nOlRwoxsDJ0_00030    1
 zbAC7t15q3k_00079    1
 Name: count, Length: 15027, dtype: int64,
 vid_name
 8qRmKunCjtY_00016    1
 jMEYIEYkpY0_00075    1
 XfCaMLlyj9I_00141    1
 XfCaMLlyj9I_00140    1
 XfCaMLlyj9I_00139    1
                     ..
 L_SB1PRgDTE_00016    1
 L_SB1PRgDTE_00015    1
 L_SB1PRgDTE_00001    1
 L_SB1PRgDTE_00000    1
 ovWCmIMMkRI_00052    1
 Name: count, Length: 1970, dtype: int64)

In [62]:
df_test.shape, df_test["vid_name"].nunique()

((1970, 4), 1970)

In [63]:
df_test.shape[0]+ df_train.shape[0]

16997

In [64]:
len(os.listdir("rgb/"))

18404

In [65]:
videoSet = df_train["vid_name"].to_list()
videoSet.extend(df_test["vid_name"].to_list())
len(videoSet)

16997

In [66]:
count = 0
for video in os.listdir("rgb/"):
    if video.split(".mp")[0] not in videoSet:
        print(f"Video not found {video}")
        count = count + 1

Video not found jMEYIEYkpY0_00112.mp4
Video not found sexZ6VnZ9yc_00030.mp4
Video not found c7FHotPDZIw_00111.mp4
Video not found c7FHotPDZIw_00105.mp4
Video not found sexZ6VnZ9yc_00024.mp4
Video not found jMEYIEYkpY0_00106.mp4
Video not found sexZ6VnZ9yc_00018.mp4
Video not found cYkUl8MrXgA_00388.mp4
Video not found bSsVWVfYU4w_00033.mp4
Video not found vlfy4cny75s_00181.mp4
Video not found 5hXbclLNSNA_00003.mp4
Video not found cYkUl8MrXgA_00411.mp4
Video not found k1F4LHeYhBs_00262.mp4
Video not found vlfy4cny75s_00195.mp4
Video not found Le6xdQ2OO8w_00052.mp4
Video not found OFxuiqI5G44_00104.mp4
Video not found VNvb5oLOpLg_01059.mp4
Video not found _8Vy3dlHg2w_00057.mp4
Video not found k71Cc-Sm-Mg_00006.mp4
Video not found JzOshOJgofw_00301.mp4
Video not found roFeEJPgJD8_00009.mp4
Video not found rRw7peH60Yw_00024.mp4
Video not found ddV_Cpszpls_00100.mp4
Video not found D8YKHC5hmUs_00116.mp4
Video not found MbzIpx8kAD0_00061.mp4
Video not found roFeEJPgJD8_00035.mp4
Video not found D6zILEKIJbk_00090.mp4
Video not found S9aCrmtAV8o_00172.mp4
Video not found zYHstCxnAPA_00119.mp4
Video not found j4gvbjifw14_00077.mp4
Video not found nOlRwoxsDJ0_00904.mp4
Video not found ddV_Cpszpls_00048.mp4
Video not found _tigfCJFLZg_00275.mp4
Video not found nOlRwoxsDJ0_00910.mp4
Video not found LNMISxO35S0_00167.mp4
Video not found S9aCrmtAV8o_00012.mp4
Video not found 3PLiUG_DuC8_00299.mp4
Video not found Q--70-ELqLw_00229.mp4
Video not found zbAC7t15q3k_00063.mp4
Video not found Y7QZcr24ye0_00200.mp4
Video not found nOlRwoxsDJ0_00737.mp4
Video not found sk8TafuB3lU_00040.mp4
Video not found bSsVWVfYU4w_00184.mp4
Video not found egsanPCCIzQ_00177.mp4
Video not found D8YKHC5hmUs_00274.mp4
Video not found ZAmJsIcfFOA_00367.mp4
Video not found V5parOfpuEQ_00125.mp4
Video not found qD3IMtAanSg_00141.mp4
Video not found l6ZoMjD1UtA_00016.mp4
Video not found qD3IMtAanSg_00140.mp4
Video not found egsanPCCIzQ_00189.mp4
Video not found ZAmJsIcfFOA_00366.mp4
Video not found D8YKHC5hmUs_00275.mp4
Video not found V5parOfpuEQ_00124.mp4
Video not found 3PLiUG_DuC8_00071.mp4
Video not found sk8TafuB3lU_00727.mp4
Video not found db7DmpqzGmc_00180.mp4
Video not found Q--70-ELqLw_00228.mp4
Video not found zYHstCxnAPA_00050.mp4
Video not found siEI_jaSmd4_00094.mp4
Video not found nOlRwoxsDJ0_00911.mp4
Video not found nOlRwoxsDJ0_00905.mp4
Video not found zYHstCxnAPA_00130.mp4
Video not found zBXtMcI41z8_00056.mp4
Video not found nOlRwoxsDJ0_00656.mp4
Video not found cYkUl8MrXgA_00174.mp4
Video not found S9aCrmtAV8o_00173.mp4
Video not found Y4ARBzok9aU_00202.mp4
Video not found CVAfPfVFulQ_00024.mp4
Video not found egsanPCCIzQ_00200.mp4
Video not found D8YKHC5hmUs_00103.mp4
Video not found JzOshOJgofw_00300.mp4
Video not found 3PLiUG_DuC8_00313.mp4
Video not found sk8TafuB3lU_01029.mp4
Video not found cYkUl8MrXgA_00438.mp4
Video not found _8Vy3dlHg2w_00042.mp4
Video not found _lmT4WlK7G0_00091.mp4
Video not found vlfy4cny75s_00194.mp4
Video not found k1F4LHeYhBs_00263.mp4
Video not found bSsVWVfYU4w_00032.mp4
Video not found 3PLiUG_DuC8_00139.mp4
Video not found sexZ6VnZ9yc_00019.mp4
Video not found cYkUl8MrXgA_00389.mp4
Video not found V5parOfpuEQ_00050.mp4
Video not found sexZ6VnZ9yc_00025.mp4
Video not found c7FHotPDZIw_00104.mp4
Video not found jMEYIEYkpY0_00107.mp4
Video not found jMEYIEYkpY0_00113.mp4
Video not found 3PLiUG_DuC8_00111.mp4
Video not found c7FHotPDZIw_00110.mp4
Video not found sexZ6VnZ9yc_00031.mp4
Video not found jMEYIEYkpY0_00105.mp4
Video not found c7FHotPDZIw_00106.mp4
Video not found sexZ6VnZ9yc_00027.mp4
Video not found sexZ6VnZ9yc_00033.mp4
Video not found c7FHotPDZIw_00112.mp4
Video not found jMEYIEYkpY0_00111.mp4
Video not found ZAmJsIcfFOA_00204.mp4
Video not found sk8TafuB3lU_01201.mp4
Video not found k1F4LHeYhBs_00261.mp4
Video not found bSsVWVfYU4w_00024.mp4
Video not found vlfy4cny75s_00196.mp4
Video not found 5hXbclLNSNA_00014.mp4
Video not found zYHstCxnAPA_00318.mp4
Video not found zYHstCxnAPA_00456.mp4
Video not found _8Vy3dlHg2w_00040.mp4
Video not found Le6xdQ2OO8w_00051.mp4
Video not found JzOshOJgofw_00302.mp4
Video not found db7DmpqzGmc_00035.mp4
Video not found OVzt2rsfMc0_00295.mp4
Video not found OFxuiqI5G44_00305.mp4
Video not found V5parOfpuEQ_00293.mp4
Video not found _tigfCJFLZg_00504.mp4
Video not found LNMISxO35S0_00158.mp4
Video not found nOlRwoxsDJ0_00907.mp4
Video not found ddV_Cpszpls_00063.mp4
Video not found ZAmJsIcfFOA_00172.mp4
Video not found Q--70-ELqLw_00202.mp4
Video not found sk8TafuB3lU_01188.mp4
Video not found Bb0ZiYVNtDs_00058.mp4
Video not found DB4lpBDPnTY_00014.mp4
Video not found 9BC6ssCjyfg_00017.mp4
Video not found 3PLiUG_DuC8_00073.mp4
Video not found V5parOfpuEQ_00126.mp4
Video not found egsanPCCIzQ_00174.mp4
Video not found xbQCwTHcGN8_00200.mp4
Video not found ZAmJsIcfFOA_00364.mp4
Video not found qD3IMtAanSg_00142.mp4
Video not found l6ZoMjD1UtA_00014.mp4
Video not found Y7QZcr24ye0_00997.mp4
Video not found Y7QZcr24ye0_00029.mp4
Video not found cYkUl8MrXgA_00214.mp4
Video not found zYHstCxnAPA_00244.mp4
Video not found _8Vy3dlHg2w_00134.mp4
Video not found 3PLiUG_DuC8_00098.mp4
Video not found bSsVWVfYU4w_00178.mp4
Video not found bSsVWVfYU4w_00179.mp4
Video not found OFxuiqI5G44_00066.mp4
Video not found cYkUl8MrXgA_00215.mp4
Video not found qD3IMtAanSg_00143.mp4
Video not found l6ZoMjD1UtA_00015.mp4
Video not found ZAmJsIcfFOA_00365.mp4
Video not found egsanPCCIzQ_00161.mp4
Video not found iv0Gu1VXAgc_00189.mp4
Video not found Y7QZcr24ye0_00799.mp4
Video not found nOlRwoxsDJ0_00735.mp4
Video not found OVzt2rsfMc0_00337.mp4
Video not found VNvb5oLOpLg_00999.mp4
Video not found Q--70-ELqLw_00203.mp4
Video not found XfCaMLlyj9I_00094.mp4
Video not found sk8TafuB3lU_01189.mp4
Video not found siEI_jaSmd4_00083.mp4
Video not found siEI_jaSmd4_00068.mp4
Video not found siEI_jaSmd4_00054.mp4
Video not found nOlRwoxsDJ0_00906.mp4
Video not found nOlRwoxsDJ0_00655.mp4
Video not found V5parOfpuEQ_00292.mp4
Video not found zYHstCxnAPA_00133.mp4
Video not found zbAC7t15q3k_00115.mp4
Video not found sk8TafuB3lU_00485.mp4
Video not found zbAC7t15q3k_00129.mp4
Video not found CVAfPfVFulQ_00027.mp4
Video not found k1F4LHeYhBs_00089.mp4
Video not found D8YKHC5hmUs_00100.mp4
Video not found Y4ARBzok9aU_00201.mp4
Video not found zBXtMcI41z8_00082.mp4
Video not found roFeEJPgJD8_00037.mp4
Video not found VNvb5oLOpLg_00806.mp4
Video not found 3PLiUG_DuC8_00310.mp4
Video not found JzOshOJgofw_00303.mp4
Video not found 5hXbclLNSNA_00001.mp4
Video not found zYHstCxnAPA_00319.mp4
Video not found vlfy4cny75s_00197.mp4
Video not found bSsVWVfYU4w_00025.mp4
Video not found _8Vy3dlHg2w_00069.mp4
Video not found sk8TafuB3lU_01200.mp4
Video not found c7FHotPDZIw_00113.mp4
Video not found sexZ6VnZ9yc_00032.mp4
Video not found vlfy4cny75s_00140.mp4
Video not found jMEYIEYkpY0_00110.mp4
Video not found sexZ6VnZ9yc_00026.mp4
Video not found _tigfCJFLZg_00101.mp4
Video not found vlfy4cny75s_00178.mp4
Video not found _8Vy3dlHg2w_00086.mp4
Video not found c7FHotPDZIw_00103.mp4
Video not found 3PLiUG_DuC8_00102.mp4
Video not found sexZ6VnZ9yc_00022.mp4
Video not found jMEYIEYkpY0_00100.mp4
Video not found sexZ6VnZ9yc_00036.mp4
Video not found Le6xdQ2OO8w_00054.mp4
Video not found Q--70-ELqLw_00159.mp4
Video not found uDESPUxbjnI_00195.mp4
Video not found k1F4LHeYhBs_00264.mp4
Video not found vlfy4cny75s_00193.mp4
Video not found VNvb5oLOpLg_01063.mp4
Video not found 6wVdnLa3Tes_00253.mp4
Video not found RWNrARSbRCY_00130.mp4
Video not found LNMISxO35S0_00015.mp4
Video not found _tigfCJFLZg_00307.mp4
Video not found fohMq9tOn6E_00020.mp4
Video not found 3PLiUG_DuC8_00314.mp4
Video not found V5parOfpuEQ_00296.mp4
Video not found iv0Gu1VXAgc_00238.mp4
Video not found zYHstCxnAPA_00080.mp4
Video not found kVT_sNgYBAE_00016.mp4
Video not found mGbuP7nT2ck_00012.mp4
Video not found D6zILEKIJbk_00121.mp4
Video not found nOlRwoxsDJ0_00902.mp4
Video not found sk8TafuB3lU_00244.mp4
Video not found siEI_jaSmd4_00087.mp4
Video not found sk8TafuB3lU_00293.mp4
Video not found Z_uFnDg-a4I_00058.mp4
Video not found sk8TafuB3lU_01199.mp4
Video not found egsanPCCIzQ_00171.mp4
Video not found Y4ARBzok9aU_00173.mp4
Video not found bSsVWVfYU4w_00182.mp4
Video not found vlfy4cny75s_00030.mp4
Video not found c7FHotPDZIw_00063.mp4
Video not found cYkUl8MrXgA_00239.mp4
Video not found sk8TafuB3lU_00907.mp4
Video not found _8Vy3dlHg2w_00119.mp4
Video not found 3N1kUtqJ25A_00270.mp4
Video not found qD3IMtAanSg_00147.mp4
Video not found sk8TafuB3lU_00085.mp4
Video not found Y7QZcr24ye0_00992.mp4
Video not found l6ZoMjD1UtA_00005.mp4
Video not found OVzt2rsfMc0_00119.mp4
Video not found 3N1kUtqJ25A_00271.mp4
Video not found _8Vy3dlHg2w_00118.mp4
Video not found Le6xdQ2OO8w_00109.mp4
Video not found qD3IMtAanSg_00146.mp4
Video not found Y7QZcr24ye0_00039.mp4
Video not found 3PLiUG_DuC8_00088.mp4
Video not found bSsVWVfYU4w_00183.mp4
Video not found 6wVdnLa3Tes_00130.mp4
Video not found egsanPCCIzQ_00170.mp4
Video not found Y4ARBzok9aU_00172.mp4
Video not found egsanPCCIzQ_00164.mp4
Video not found Z_uFnDg-a4I_00059.mp4
Video not found sk8TafuB3lU_01198.mp4
Video not found sk8TafuB3lU_00292.mp4
Video not found siEI_jaSmd4_00086.mp4
Video not found Z_uFnDg-a4I_00065.mp4
Video not found Y7QZcr24ye0_00213.mp4
Video not found Y7QZcr24ye0_00207.mp4
Video not found DB4lpBDPnTY_00038.mp4
Video not found nOlRwoxsDJ0_00903.mp4
Video not found sk8TafuB3lU_00245.mp4
Video not found 2x00lRzlTVQ_00109.mp4
Video not found D6zILEKIJbk_00134.mp4
Video not found xbQCwTHcGN8_00006.mp4
Video not found 2x00lRzlTVQ_00135.mp4
Video not found ddV_Cpszpls_00073.mp4
Video not found iv0Gu1VXAgc_00205.mp4
Video not found V5parOfpuEQ_00297.mp4
Video not found zbAC7t15q3k_00104.mp4
Video not found 2x00lRzlTVQ_00082.mp4
Video not found -mmq0PT-u8k_00109.mp4
Video not found zYHstCxnAPA_00687.mp4
Video not found ddV_Cpszpls_00113.mp4
Video not found sk8TafuB3lU_00696.mp4
Video not found vlfy4cny75s_00192.mp4
Video not found qD3IMtAanSg_00032.mp4
Video not found k1F4LHeYhBs_00265.mp4
Video not found 6wVdnLa3Tes_00087.mp4
Video not found zYHstCxnAPA_00446.mp4
Video not found Q--70-ELqLw_00158.mp4
Video not found sexZ6VnZ9yc_00037.mp4
Video not found sexZ6VnZ9yc_00023.mp4
Video not found jMEYIEYkpY0_00101.mp4
Video not found vlfy4cny75s_00179.mp4
Video not found OVzt2rsfMc0_00093.mp4
Video not found _8Vy3dlHg2w_00087.mp4
Video not found D6zILEKIJbk_00268.mp4
Video not found sexZ6VnZ9yc_00009.mp4
Video not found 6wVdnLa3Tes_00046.mp4
Video not found LNMISxO35S0_00200.mp4
Video not found egsanPCCIzQ_00012.mp4
Video not found sexZ6VnZ9yc_00035.mp4
Video not found c7FHotPDZIw_00114.mp4
Video not found _lmT4WlK7G0_00056.mp4
Video not found sexZ6VnZ9yc_00021.mp4
Video not found Le6xdQ2OO8w_00057.mp4
Video not found VNvb5oLOpLg_00356.mp4
Video not found qD3IMtAanSg_00030.mp4
Video not found vlfy4cny75s_00190.mp4
Video not found Q--70-ELqLw_00172.mp4
Video not found uDESPUxbjnI_00196.mp4
Video not found nOlRwoxsDJ0_00478.mp4
Video not found l6ZoMjD1UtA_00166.mp4
Video not found 2x00lRzlTVQ_00043.mp4
Video not found zYHstCxnAPA_00685.mp4
Video not found RWNrARSbRCY_00127.mp4
Video not found nOlRwoxsDJ0_00685.mp4
Video not found ddV_Cpszpls_00111.mp4
Video not found 3PLiUG_DuC8_00317.mp4
Video not found MbzIpx8kAD0_00058.mp4
Video not found VNvb5oLOpLg_00815.mp4
Video not found zYHstCxnAPA_00120.mp4
Video not found zbAC7t15q3k_00106.mp4
Video not found V5parOfpuEQ_00295.mp4
Video not found cs8g1es4vfM_00012.mp4
Video not found V5parOfpuEQ_00281.mp4
Video not found Le6xdQ2OO8w_00269.mp4
Video not found 2x00lRzlTVQ_00137.mp4
Video not found XfCaMLlyj9I_00078.mp4
Video not found ddV_Cpszpls_00065.mp4
Video not found _tigfCJFLZg_00502.mp4
Video not found fohMq9tOn6E_00143.mp4
Video not found XfCaMLlyj9I_00050.mp4
Video not found zYHstCxnAPA_00040.mp4
Video not found j4gvbjifw14_00112.mp4
Video not found siEI_jaSmd4_00090.mp4
Video not found Q--70-ELqLw_00204.mp4
Video not found egsanPCCIzQ_00172.mp4
Video not found egsanPCCIzQ_00166.mp4
Video not found bSsVWVfYU4w_00181.mp4
Video not found mGRum47TLX0_00017.mp4
Video not found k71Cc-Sm-Mg_00188.mp4
Video not found D8YKHC5hmUs_00259.mp4
Video not found _tigfCJFLZg_00072.mp4
Video not found zYHstCxnAPA_00256.mp4
Video not found Le6xdQ2OO8w_00123.mp4
Video not found jMEYIEYkpY0_00088.mp4
Video not found qD3IMtAanSg_00150.mp4
Video not found egsanPCCIzQ_00199.mp4
Video not found qD3IMtAanSg_00144.mp4
Video not found 3N1kUtqJ25A_00273.mp4
Video not found qD3IMtAanSg_00145.mp4
Video not found egsanPCCIzQ_00198.mp4
Video not found 3N1kUtqJ25A_00272.mp4
Video not found 8qRmKunCjtY_00015.mp4
Video not found Le6xdQ2OO8w_00122.mp4
Video not found k71Cc-Sm-Mg_00189.mp4
Video not found 3PLiUG_DuC8_00060.mp4
Video not found bSsVWVfYU4w_00180.mp4
Video not found j4gvbjifw14_00107.mp4
Video not found RWNrARSbRCY_00085.mp4
Video not found D6zILEKIJbk_00137.mp4
Video not found _tigfCJFLZg_00271.mp4
Video not found siEI_jaSmd4_00046.mp4
Video not found Bb0ZiYVNtDs_00088.mp4
Video not found _tigfCJFLZg_00503.mp4
Video not found OFxuiqI5G44_00289.mp4
Video not found fohMq9tOn6E_00142.mp4
Video not found xbQCwTHcGN8_00005.mp4
Video not found 2x00lRzlTVQ_00136.mp4
Video not found ddV_Cpszpls_00070.mp4
Video not found Le6xdQ2OO8w_00268.mp4
Video not found cs8g1es4vfM_00013.mp4
Video not found V5parOfpuEQ_00294.mp4
Video not found sk8TafuB3lU_00454.mp4
Video not found ddV_Cpszpls_00110.mp4
Video not found vlfy4cny75s_00191.mp4
Video not found qD3IMtAanSg_00031.mp4
Video not found k1F4LHeYhBs_00266.mp4
Video not found uDESPUxbjnI_00197.mp4
Video not found l6ZoMjD1UtA_00173.mp4
Video not found cYkUl8MrXgA_00429.mp4
Video not found VNvb5oLOpLg_00357.mp4
Video not found VNvb5oLOpLg_00343.mp4
Video not found _8Vy3dlHg2w_00047.mp4
Video not found sexZ6VnZ9yc_00020.mp4
Video not found sk8TafuB3lU_00656.mp4
Video not found c7FHotPDZIw_00115.mp4
Video not found sexZ6VnZ9yc_00034.mp4
Video not found Y7QZcr24ye0_00199.mp4
Video not found eN8umEok9U8_00185.mp4
Video not found sexZ6VnZ9yc_00008.mp4
Video not found D6zILEKIJbk_00232.mp4
Video not found 3PLiUG_DuC8_00173.mp4
Video not found sexZ6VnZ9yc_00053.mp4
Video not found sk8TafuB3lU_00157.mp4
Video not found egsanPCCIzQ_00048.mp4
Video not found sexZ6VnZ9yc_00047.mp4
Video not found JzOshOJgofw_00148.mp4
Video not found Y4ARBzok9aU_00062.mp4
Video not found sk8TafuB3lU_00194.mp4
Video not found LNMISxO35S0_00299.mp4
Video not found sk8TafuB3lU_00180.mp4
Video not found Y7QZcr24ye0_00101.mp4
Video not found iv0Gu1VXAgc_00077.mp4
Video not found D6zILEKIJbk_00030.mp4
Video not found XfCaMLlyj9I_00156.mp4
Video not found XfCaMLlyj9I_00142.mp4
Video not found sk8TafuB3lU_01077.mp4
Video not found D8YKHC5hmUs_00161.mp4
Video not found RWNrARSbRCY_00141.mp4
Video not found 2x00lRzlTVQ_00031.mp4
Video not found ddV_Cpszpls_00177.mp4
Video not found Y7QZcr24ye0_01021.mp4
Video not found nOlRwoxsDJ0_00608.mp4
Video not found Y7QZcr24ye0_01035.mp4
Video not found CVAfPfVFulQ_00085.mp4
Video not found _8Vy3dlHg2w_00222.mp4
Video not found Y7QZcr24ye0_00471.mp4
Video not found OVzt2rsfMc0_00222.mp4
Video not found zYHstCxnAPA_00152.mp4
Video not found Y7QZcr24ye0_01009.mp4
Video not found Y7QZcr24ye0_00288.mp4
Video not found fohMq9tOn6E_00125.mp4
Video not found D8YKHC5hmUs_00001.mp4
Video not found S9aCrmtAV8o_00071.mp4
Video not found S9aCrmtAV8o_00059.mp4
Video not found ddV_Cpszpls_00229.mp4
Video not found vlfy4cny75s_00055.mp4
Video not found 3PLiUG_DuC8_00013.mp4
Video not found _8Vy3dlHg2w_00197.mp4
Video not found egsanPCCIzQ_00100.mp4
Video not found D8YKHC5hmUs_00203.mp4
Video not found OVzt2rsfMc0_00197.mp4
Video not found czXA41QTops_00114.mp4
Video not found _8Vy3dlHg2w_00168.mp4
Video not found cYkUl8MrXgA_00512.mp4
Video not found k71Cc-Sm-Mg_00139.mp4
Video not found cYkUl8MrXgA_00506.mp4
Video not found zYHstCxnAPA_00543.mp4
Video not found VNvb5oLOpLg_00251.mp4
Video not found sk8TafuB3lU_00963.mp4
Video not found cYkUl8MrXgA_00507.mp4
Video not found cYkUl8MrXgA_00513.mp4
Video not found _8Vy3dlHg2w_00169.mp4
Video not found k71Cc-Sm-Mg_00138.mp4
Video not found Y7QZcr24ye0_00048.mp4
Video not found czXA41QTops_00115.mp4
Video not found Y4ARBzok9aU_00103.mp4
Video not found xbQCwTHcGN8_00249.mp4
Video not found 3PLiUG_DuC8_00006.mp4
Video not found OVzt2rsfMc0_00425.mp4
Video not found nOlRwoxsDJ0_00741.mp4
Video not found D6zILEKIJbk_00192.mp4
Video not found zYHstCxnAPA_00782.mp4
Video not found ddV_Cpszpls_00016.mp4
Video not found -mmq0PT-u8k_00018.mp4
Video not found LNMISxO35S0_00139.mp4
Video not found Y7QZcr24ye0_00289.mp4
Video not found fohMq9tOn6E_00124.mp4
Video not found Y7QZcr24ye0_01008.mp4
Video not found zYHstCxnAPA_00153.mp4
Video not found _8Vy3dlHg2w_00223.mp4
Video not found ddV_Cpszpls_00189.mp4
Video not found Y7QZcr24ye0_01034.mp4
Video not found Y7QZcr24ye0_01020.mp4
Video not found sFO6XlfgxNQ_00099.mp4
Video not found 2x00lRzlTVQ_00030.mp4
Video not found V5parOfpuEQ_00219.mp4
Video not found VNvb5oLOpLg_00872.mp4
Video not found OVzt2rsfMc0_00021.mp4
Video not found LNMISxO35S0_00298.mp4
Video not found uDESPUxbjnI_00132.mp4
Video not found sexZ6VnZ9yc_00046.mp4
Video not found sexZ6VnZ9yc_00052.mp4
Video not found sk8TafuB3lU_00156.mp4
Video not found sexZ6VnZ9yc_00044.mp4
Video not found sk8TafuB3lU_00154.mp4
Video not found _tigfCJFLZg_00177.mp4
Video not found sexZ6VnZ9yc_00050.mp4
Video not found 3PLiUG_DuC8_00158.mp4
Video not found egsanPCCIzQ_00077.mp4
Video not found 6wVdnLa3Tes_00023.mp4
Video not found cYkUl8MrXgA_00471.mp4
Video not found qD3IMtAanSg_00055.mp4
Video not found ZAmJsIcfFOA_00298.mp4
Video not found VNvb5oLOpLg_00455.mp4
Video not found zYHstCxnAPA_00353.mp4
Video not found Y7QZcr24ye0_00102.mp4
Video not found cYkUl8MrXgA_00459.mp4
Video not found _8Vy3dlHg2w_00023.mp4
Video not found ZAmJsIcfFOA_00059.mp4
Video not found D6zILEKIJbk_00033.mp4
Video not found sk8TafuB3lU_01048.mp4
Video not found -mmq0PT-u8k_00146.mp4
Video not found ddV_Cpszpls_00174.mp4
Video not found RWNrARSbRCY_00142.mp4
Video not found zYHstCxnAPA_00838.mp4
Video not found CVAfPfVFulQ_00045.mp4
Video not found 6wVdnLa3Tes_00221.mp4
Video not found LNMISxO35S0_00073.mp4
Video not found Y7QZcr24ye0_01036.mp4
Video not found Y7QZcr24ye0_01022.mp4
Video not found Bb0ZiYVNtDs_00173.mp4
Video not found CVAfPfVFulQ_00086.mp4
Video not found j4gvbjifw14_00017.mp4
Video not found kVT_sNgYBAE_00058.mp4
Video not found sk8TafuB3lU_00593.mp4
Video not found OVzt2rsfMc0_00427.mp4
Video not found 3PLiUG_DuC8_00010.mp4
Video not found mGRum47TLX0_00066.mp4
Video not found 5i1begTTucc_00063.mp4
Video not found 3PLiUG_DuC8_00004.mp4
Video not found c7FHotPDZIw_00005.mp4
Video not found V5parOfpuEQ_00179.mp4
Video not found Y4ARBzok9aU_00129.mp4
Video not found egsanPCCIzQ_00103.mp4
Video not found ZAmJsIcfFOA_00313.mp4
Video not found ddV_Cpszpls_00216.mp4
Video not found cYkUl8MrXgA_00505.mp4
Video not found cYkUl8MrXgA_00511.mp4
Video not found _8Vy3dlHg2w_00143.mp4
Video not found VNvb5oLOpLg_00247.mp4
Video not found VNvb5oLOpLg_01159.mp4
Video not found qD3IMtAanSg_00109.mp4
Video not found sk8TafuB3lU_00961.mp4
Video not found zYHstCxnAPA_00555.mp4
Video not found VNvb5oLOpLg_01158.mp4
Video not found cYkUl8MrXgA_00276.mp4
Video not found cYkUl8MrXgA_00510.mp4
Video not found cYkUl8MrXgA_00504.mp4
Video not found egsanPCCIzQ_00116.mp4
Video not found OVzt2rsfMc0_00195.mp4
Video not found V5parOfpuEQ_00150.mp4
Video not found 6wVdnLa3Tes_00142.mp4
Video not found sk8TafuB3lU_00021.mp4
Video not found 3PLiUG_DuC8_00011.mp4
Video not found _tigfCJFLZg_00016.mp4
Video not found OVzt2rsfMc0_00340.mp4
Video not found S9aCrmtAV8o_00067.mp4
Video not found Y7QZcr24ye0_00249.mp4
Video not found -mmq0PT-u8k_00033.mp4
Video not found XfCaMLlyj9I_00020.mp4
Video not found xbQCwTHcGN8_00048.mp4
Video not found CVAfPfVFulQ_00087.mp4
Video not found Y7QZcr24ye0_01023.mp4
Video not found Y7QZcr24ye0_01037.mp4
Video not found zYHstCxnAPA_00839.mp4
Video not found roFeEJPgJD8_00040.mp4

In [67]:
print(count)

1407

In [68]:
df = pd.concat([df_train, df_test], ignore_index=True)
print(df.shape)
print(df.head())

(16997, 4)
            vid_name  label  start_frame  end_frame
0  -mmq0PT-u8k_00155      0            0         48
1  -mmq0PT-u8k_00156      0            0         70
2  -mmq0PT-u8k_00157      0            0         90
3  3qq031609lA_00002      0            0        123
4  3qq031609lA_00004      0            0        102

In [69]:
df['vid_name'].value_counts()

vid_name
-mmq0PT-u8k_00155    1
_tigfCJFLZg_00057    1
Z_uFnDg-a4I_00106    1
Z_uFnDg-a4I_00107    1
Z_uFnDg-a4I_00108    1
                    ..
OVzt2rsfMc0_00074    1
OVzt2rsfMc0_00075    1
OVzt2rsfMc0_00120    1
OVzt2rsfMc0_00121    1
ovWCmIMMkRI_00052    1
Name: count, Length: 16997, dtype: int64

In [70]:
count = 0
df["exists"] = False
for video in os.listdir("FullAnnotated1000/"):
    base = os.path.splitext(video)[0] 
    vid_name = base.removeprefix("queries_")
    if vid_name in videoSet:
        df.loc[df["vid_name"] == vid_name, "exists"] = True
        count += 1

In [71]:
count

7945

In [47]:
df.loc[df["exists"]==True,"label"].value_counts()

label
7     562
35    541
26    510
46    382
45    370
33    335
15    330
21    329
34    303
31    292
24    246
19    240
22    237
43    236
12    230
44    223
8     217
5     209
36    203
28    189
0     159
3     150
29    117
27    107
6     107
17    106
11     89
42     85
1      79
32     73
41     71
9      68
16     59
47     57
14     44
4      44
25     43
18     39
23     36
20     35
10     34
40     33
37     32
38     27
39     23
13     23
2      21
Name: count, dtype: int64

In [48]:
df["label"].value_counts()

label
26    1122
35    1087
46     979
7      964
31     771
21     741
15     724
19     721
34     670
45     616
33     607
44     585
24     564
5      508
8      478
12     449
36     427
43     415
22     407
28     377
17     370
0      295
3      290
27     289
29     251
9      214
6      181
20     179
41     170
11     161
1      156
42     133
14     104
32     104
38      93
10      89
16      87
18      82
47      76
37      73
23      64
25      62
13      56
4       54
2       52
40      50
39      50
Name: count, dtype: int64

In [14]:
total_counts = df["label"].value_counts().sort_index()

exists_counts = df.loc[df["exists"] == True, "label"].value_counts().sort_index()

loss_df = pd.DataFrame({
    "total_count": total_counts,
    "exists_count": exists_counts
})

loss_df["exists_count"] = loss_df["exists_count"].fillna(0).astype(int)

loss_df["lost_count"] = loss_df["total_count"] - loss_df["exists_count"]
loss_df["percent_lost"] = 100 * loss_df["lost_count"] / loss_df["total_count"]

loss_df["percent_lost"] = loss_df["percent_lost"].round(2)

loss_df

       total_count  exists_count  lost_count  percent_lost
label
0              295           159         136         46.10
1              156            79          77         49.36
2               52            21          31         59.62
3              290           150         140         48.28
4               54            44          10         18.52
5              508           209         299         58.86
6              181           107          74         40.88
7              964           562         402         41.70
8              478           217         261         54.60
9              214            68         146         68.22
10              89            34          55         61.80
11             161            89          72         44.72
12             449           230         219         48.78
13              56            23          33         58.93
14             104            44          60         57.69
15             724           330         394         54.42
16              87            59          28         32.18
17             370           106         264         71.35
18              82            39          43         52.44
19             721           240         481         66.71
20             179            35         144         80.45
21             741           329         412         55.60
22             407           237         170         41.77
23              64            36          28         43.75
24             564           246         318         56.38
25              62            43          19         30.65
26            1122           510         612         54.55
27             289           107         182         62.98
28             377           189         188         49.87
29             251           117         134         53.39
31             771           292         479         62.13
32             104            73          31         29.81
33             607           335         272         44.81
34             670           303         367         54.78
35            1087           541         546         50.23
36             427           203         224         52.46
37              73            32          41         56.16
38              93            27          66         70.97
39              50            23          27         54.00
40              50            33          17         34.00
41             170            71          99         58.24
42             133            85          48         36.09
43             415           236         179         43.13
44             585           223         362         61.88
45             616           370         246         39.94
46             979           382         597         60.98
47              76            57          19         25.00

In [15]:
loss_df["percent_lost"].mean()

np.float64(51.045957446808515)

In [72]:
NotProperlyProcessed = pd.read_csv("NotProperlyProcessed.csv")
NotProperlyProcessed

                 Names
0    iv0Gu1VXAgc_00025
1    VNvb5oLOpLg_00376
2    j4gvbjifw14_00091
3    Y7QZcr24ye0_00392
4    -mmq0PT-u8k_00103
..                 ...
474  Y7QZcr24ye0_00241
475  sk8TafuB3lU_00559
476  XfCaMLlyj9I_00028
477  ddV_Cpszpls_00009
478  3PLiUG_DuC8_00227

[479 rows x 1 columns]

In [42]:
def clean_queries_prefix(df, column_name):
    """
    Removes 'queries_' prefix from a specific column in the dataframe and 
    adds a new boolean column 'Not well Processed' indicating whether it was removed.
    
    Parameters:
    - df: pandas.DataFrame
    - column_name: str, name of the column to process (e.g., 'vid_name')
    
    Returns:
    - df: updated DataFrame with cleaned column and 'Not well Processed' flag
    """
    # Create boolean mask for entries that have 'queries_' prefix
    mask = df[column_name].str.startswith("queries_")

    # Remove prefix if present
    df[column_name] = df[column_name].str.removeprefix("queries_")

    # Add new column indicating if prefix was originally present
    df["Not well Processed"] = mask

    return df

In [73]:
NotProperlyProcessed["vid_name_cleaned"] = NotProperlyProcessed["Names"].str.removeprefix("queries_")

# Step 2: Merge with df to get label
bad_processed_with_labels = NotProperlyProcessed.merge(
    df[["vid_name", "label"]],
    left_on="vid_name_cleaned",
    right_on="vid_name",
    how="inner"
)

# Step 3: Count how many not well processed per label
not_well_processed_counts = bad_processed_with_labels["label"].value_counts().sort_index()

# Step 4: Merge into your existing loss_df
loss_df["not_well_processed_count"] = not_well_processed_counts
loss_df["not_well_processed_count"] = loss_df["not_well_processed_count"].fillna(0).astype(int)

# Display updated table
loss_df

,total_count,exists_count,lost_count,percent_lost,not_well_processed_count,percent_exist_actual,percent_lost_actual,lost_countIteration2
label,,,,,,,,
0,295,159,136,46.10,4,52.54,47.46,155
1,156,79,77,49.36,4,48.08,51.92,75
2,52,21,31,59.62,2,36.54,63.46,19
3,290,150,140,48.28,15,46.55,53.45,135
4,54,44,10,18.52,0,81.48,18.52,44
5,508,209,299,58.86,4,40.35,59.65,205
6,181,107,74,40.88,2,58.01,41.99,105
7,964,562,402,41.70,39,54.36,45.64,524
8,478,217,261,54.60,5,44.35,55.65,212
9,214,68,146,68.22,7,28.50,71.50,61
10,89,34,55,61.80,6,31.46,68.54,28
11,161,89,72,44.72,4,52.80,47.20,85
12,449,230,219,48.78,12,48.55,51.45,218
13,56,23,33,58.93,4,33.93,66.07,19
14,104,44,60,57.69,9,33.65,66.35,35
15,724,330,394,54.42,33,41.02,58.98,297
16,87,59,28,32.18,5,62.07,37.93,54
17,370,106,264,71.35,7,26.76,73.24,99
18,82,39,43,52.44,2,45.12,54.88,37
19,721,240,481,66.71,17,30.93,69.07,223
20,179,35,144,80.45,2,18.44,81.56,33
21,741,329,412,55.60,18,41.97,58.03,311
22,407,237,170,41.77,13,55.04,44.96,224
23,64,36,28,43.75,1,54.69,45.31,35
24,564,246,318,56.38,15,40.96,59.04,231
25,62,43,19,30.65,1,67.74,32.26,42
26,1122,510,612,54.55,22,43.49,56.51,488
27,289,107,182,62.98,3,35.99,64.01,104
28,377,189,188,49.87,9,47.75,52.25,180
29,251,117,134,53.39,5,44.62,55.38,112
31,771,292,479,62.13,12,36.45,63.55,281
32,104,73,31,29.81,1,69.23,30.77,72
33,607,335,272,44.81,28,50.58,49.42,307
34,670,303,367,54.78,10,43.73,56.27,293
35,1087,541,546,50.23,23,47.65,52.35,518
36,427,203,224,52.46,9,45.43,54.57,194
37,73,32,41,56.16,1,42.47,57.53,31
38,93,27,66,70.97,3,25.81,74.19,24
39,50,23,27,54.00,2,42.00,58.00,21
40,50,33,17,34.00,2,62.00,38.00,31
41,170,71,99,58.24,4,40.59,59.41,69
42,133,85,48,36.09,4,60.90,39.10,81
43,415,236,179,43.13,10,54.46,45.54,226
44,585,223,362,61.88,7,36.92,63.08,216
45,616,370,246,39.94,18,57.14,42.86,352
46,979,382,597,60.98,22,36.77,63.23,360
47,76,57,19,25.00,1,73.68,26.32,56

In [52]:
not_proper_names = NotProperlyProcessed["Names"].astype(str).tolist()

In [74]:
loss_df["not_well_processed_count"].sum()

np.int64(427)

In [75]:
len(not_proper_names)

479

In [24]:
loss_df["total_count"] = loss_df["total_count"].astype(int)
loss_df["exists_count"] = loss_df["exists_count"].astype(int)
loss_df["not_well_processed_count"] = loss_df["not_well_processed_count"].astype(int)

loss_df["percent_exist_actual"] = (
   (100 * (( loss_df["total_count"] - loss_df["lost_count"] - loss_df["not_well_processed_count"] ) / loss_df["total_count"])).round(2)
)

loss_df["percent_lost_actual"] = (
   (100 * (( loss_df["lost_count"] + loss_df["not_well_processed_count"] ) / loss_df["total_count"] )).round(2)
)

loss_df["lost_countIteration2"] = (
    loss_df["total_count"] - loss_df["lost_count"] - loss_df["not_well_processed_count"]
).astype(int)

loss_df

,total_count,exists_count,lost_count,percent_lost,not_well_processed_count,percent_exist_actual,percent_lost_actual,lost_countIteration2
label,,,,,,,,
0,295,159,136,46.10,4,52.54,47.46,155
1,156,79,77,49.36,4,48.08,51.92,75
2,52,21,31,59.62,2,36.54,63.46,19
3,290,150,140,48.28,15,46.55,53.45,135
4,54,44,10,18.52,0,81.48,18.52,44
5,508,209,299,58.86,4,40.35,59.65,205
6,181,107,74,40.88,2,58.01,41.99,105
7,964,562,402,41.70,38,54.36,45.64,524
8,478,217,261,54.60,5,44.35,55.65,212
9,214,68,146,68.22,7,28.50,71.50,61
10,89,34,55,61.80,6,31.46,68.54,28
11,161,89,72,44.72,4,52.80,47.20,85
12,449,230,219,48.78,12,48.55,51.45,218
13,56,23,33,58.93,4,33.93,66.07,19
14,104,44,60,57.69,9,33.65,66.35,35
15,724,330,394,54.42,33,41.02,58.98,297
16,87,59,28,32.18,5,62.07,37.93,54
17,370,106,264,71.35,7,26.76,73.24,99
18,82,39,43,52.44,2,45.12,54.88,37
19,721,240,481,66.71,17,30.93,69.07,223
20,179,35,144,80.45,2,18.44,81.56,33
21,741,329,412,55.60,18,41.97,58.03,311
22,407,237,170,41.77,13,55.04,44.96,224
23,64,36,28,43.75,1,54.69,45.31,35
24,564,246,318,56.38,15,40.96,59.04,231
25,62,43,19,30.65,1,67.74,32.26,42
26,1122,510,612,54.55,22,43.49,56.51,488
27,289,107,182,62.98,3,35.99,64.01,104
28,377,189,188,49.87,9,47.75,52.25,180
29,251,117,134,53.39,5,44.62,55.38,112
31,771,292,479,62.13,11,36.45,63.55,281
32,104,73,31,29.81,1,69.23,30.77,72
33,607,335,272,44.81,28,50.58,49.42,307
34,670,303,367,54.78,10,43.73,56.27,293
35,1087,541,546,50.23,23,47.65,52.35,518
36,427,203,224,52.46,9,45.43,54.57,194
37,73,32,41,56.16,1,42.47,57.53,31
38,93,27,66,70.97,3,25.81,74.19,24
39,50,23,27,54.00,2,42.00,58.00,21
40,50,33,17,34.00,2,62.00,38.00,31
41,170,71,99,58.24,2,40.59,59.41,69
42,133,85,48,36.09,4,60.90,39.10,81
43,415,236,179,43.13,10,54.46,45.54,226
44,585,223,362,61.88,7,36.92,63.08,216
45,616,370,246,39.94,18,57.14,42.86,352
46,979,382,597,60.98,22,36.77,63.23,360
47,76,57,19,25.00,1,73.68,26.32,56

In [77]:
df['vid_name'].value_counts()

vid_name
-mmq0PT-u8k_00155    1
_tigfCJFLZg_00057    1
Z_uFnDg-a4I_00106    1
Z_uFnDg-a4I_00107    1
Z_uFnDg-a4I_00108    1
                    ..
OVzt2rsfMc0_00074    1
OVzt2rsfMc0_00075    1
OVzt2rsfMc0_00120    1
OVzt2rsfMc0_00121    1
ovWCmIMMkRI_00052    1
Name: count, Length: 16997, dtype: int64

In [78]:
df["exists"].value_counts()

exists
False    9052
True     7945
Name: count, dtype: int64

In [79]:
df.loc[df["vid_name"].isin(not_proper_names), "exists"] = False

In [80]:
# df = pd.read_csv("ActualPreprocessedWithClass.csv")
df["exists"].value_counts()

exists
False    9450
True     7547
Name: count, dtype: int64

In [81]:
df['vid_name'].value_counts()

vid_name
-mmq0PT-u8k_00155    1
_tigfCJFLZg_00057    1
Z_uFnDg-a4I_00106    1
Z_uFnDg-a4I_00107    1
Z_uFnDg-a4I_00108    1
                    ..
OVzt2rsfMc0_00074    1
OVzt2rsfMc0_00075    1
OVzt2rsfMc0_00120    1
OVzt2rsfMc0_00121    1
ovWCmIMMkRI_00052    1
Name: count, Length: 16997, dtype: int64

In [82]:
df_exists = df[df["exists"] == True].copy()

# from sklearn.utils.class_weight import compute_class_weight
# import numpy as np

# labels = df_exists["label"].astype(int)

# classes = np.unique(labels)

# weights = compute_class_weight(class_weight="balanced", classes=classes, y=labels)

# class_weights = dict(zip(classes, weights))

In [83]:
df_exists.to_csv("df_exists1.csv")

In [85]:
df_exists[:381]

              vid_name  label  start_frame  end_frame  exists
0    -mmq0PT-u8k_00155      0            0         48    True
3    3qq031609lA_00002      0            0        123    True
4    3qq031609lA_00004      0            0        102    True
5    5V-dKBtmKLI_00018      0            0         55    True
7    5V-dKBtmKLI_00085      0            0         80    True
..                 ...    ...          ...        ...     ...
939  ZAmJsIcfFOA_00305      5            0         61    True
940  ZAmJsIcfFOA_00306      5            0        157    True
944  ZAmJsIcfFOA_00320      5            0        164    True
947  ZAmJsIcfFOA_00324      5            0         64    True
948  ZAmJsIcfFOA_00325      5            0        174    True

[381 rows x 5 columns]

In [33]:
print("Filtered DataFrame shape:", df_exists.shape)
print("Class Weights:", class_weights)

Filtered DataFrame shape: (7071, 6)
Class Weights: {np.int64(0): np.float64(1.0375641966250917), np.int64(1): np.float64(2.0330649798734903), np.int64(2): np.float64(9.402925531914894), np.int64(3): np.float64(1.3082331174838113), np.int64(4): np.float64(3.4192456479690523), np.int64(5): np.float64(0.7835771276595744), np.int64(6): np.float64(1.4895723614914682), np.int64(7): np.float64(0.3045481953656646), np.int64(8): np.float64(0.7522340425531915), np.int64(9): np.float64(3.070343030829353), np.int64(10): np.float64(5.786415711947627), np.int64(11): np.float64(1.8805851063829788), np.int64(12): np.float64(0.7164133738601823), np.int64(13): np.float64(10.029787234042553), np.int64(14): np.float64(4.55899419729207), np.int64(15): np.float64(0.5316141643485452), np.int64(16): np.float64(2.8932078559738135), np.int64(17): np.float64(1.6716312056737588), np.int64(18): np.float64(4.55899419729207), np.int64(19): np.float64(0.7096547571256524), np.int64(20): np.float64(4.701462765957447), np.int64(21): np.float64(0.5392358727979867), np.int64(22): np.float64(0.7096547571256524), np.int64(23): np.float64(4.55899419729207), np.int64(24): np.float64(0.7374843554443054), np.int64(25): np.float64(3.582066869300912), np.int64(26): np.float64(0.32146753955264595), np.int64(27): np.float64(1.504468085106383), np.int64(28): np.float64(0.8646368305209098), np.int64(29): np.float64(1.4749687108886107), np.int64(31): np.float64(0.5698742746615088), np.int64(32): np.float64(2.118969133952652), np.int64(33): np.float64(0.5134703362137826), np.int64(34): np.float64(0.5373100303951368), np.int64(35): np.float64(0.30956133438402944), np.int64(36): np.float64(0.822113707708406), np.int64(37): np.float64(5.014893617021277), np.int64(38): np.float64(6.838491295938105), np.int64(39): np.float64(7.522340425531915), np.int64(40): np.float64(4.853122855181881), np.int64(41): np.float64(2.786052009456265), np.int64(42): np.float64(1.9795632698768197), np.int64(43): np.float64(0.6933032650259829), np.int64(44): np.float64(0.7447861807457341), np.int64(45): np.float64(0.446429698844624), np.int64(46): np.float64(0.44249061326658323), np.int64(47): np.float64(2.7353965183752416)}

In [69]:
for i in class_weights:
    print(i, class_weights[i])

0 1.0306033226464588
1 2.0333525014376077
2 9.404255319148936
3 1.308418131359852
4 3.4197292069632494
5 0.7836879432624113
6 1.489783020855277
7 0.3045912653975364
8 0.7523404255319149
9 3.0707772470690404
10 5.787234042553192
11 1.8808510638297873
12 0.7165146909827761
13 10.031205673758866
14 4.559638942617666
15 0.5316893466656643
16 2.893617021276596
17 1.6718676122931442
18 4.559638942617666
19 0.7097551184263348
20 4.702127659574468
21 0.5393121329977885
22 0.7097551184263348
23 4.559638942617666
24 0.7375886524822695
25 3.5825734549138804
26 0.3215130023640662
27 1.5046808510638299
28 0.8647591098067987
29 1.475177304964539
31 0.5699548678272083
32 2.1192688043152534
33 0.5135429525815118
34 0.5373860182370821
35 0.3096051133876193
36 0.8222299732589233
37 5.015602836879433
38 6.839458413926499
39 7.523404255319149
40 4.853809196980096
41 2.7864460204885737
42 1.9798432250839866
43 0.6934013138542995
44 0.7448915104276385
45 0.44649283414356966
46 0.4425531914893617
47 2.7357833655705996

In [74]:
df_exists.reset_index().drop(columns=["index","exists"]).to_csv("df_exsists.csv")

In [75]:
df_exists

                vid_name  label  start_frame  end_frame  exists
3      3qq031609lA_00002      0            0        123    True
4      3qq031609lA_00004      0            0        102    True
5      5V-dKBtmKLI_00018      0            0         55    True
7      5V-dKBtmKLI_00085      0            0         80    True
8      5V-dKBtmKLI_00086      0            0         89    True
...                  ...    ...          ...        ...     ...
16992  mGRum47TLX0_00040     47            0         56    True
16993  mGRum47TLX0_00044     47            0        112    True
16994  ovWCmIMMkRI_00050     47            0        108    True
16995  ovWCmIMMkRI_00051     47            0        125    True
16996  ovWCmIMMkRI_00052     47            0         91    True

[7072 rows x 5 columns]

In [76]:
df_exists["label"].value_counts()

label
7     494
35    486
26    468
46    340
45    337
33    293
15    283
34    280
21    279
31    264
43    217
22    212
19    212
12    210
24    204
44    202
8     200
5     192
36    183
28    174
0     146
3     115
29    102
6     101
27    100
17     90
11     80
42     76
1      74
32     71
47     55
41     54
16     52
9      49
4      44
25     42
18     33
14     33
23     33
20     32
40     31
37     30
10     26
38     22
39     20
2      16
13     15
Name: count, dtype: int64

In [81]:
np.sort(df_exists["label"].value_counts().index)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [97]:
ActualPreprocessedWithClass = pd.read_csv("ActualPreprocessedWithClass.csv")

In [98]:
mask = (ActualPreprocessedWithClass['exists']==True)
ActualPreprocessedWithClass[mask]['vid_name'].value_counts()

vid_name
#NAME?               64
j4gvbjifw14_00074     1
mGbuP7nT2ck_00158     1
mGbuP7nT2ck_00157     1
mGbuP7nT2ck_00156     1
                     ..
vlfy4cny75s_00109     1
vlfy4cny75s_00108     1
vlfy4cny75s_00107     1
vlfy4cny75s_00106     1
ovWCmIMMkRI_00052     1
Name: count, Length: 7008, dtype: int64

In [101]:
df1 = ActualPreprocessedWithClass[ActualPreprocessedWithClass['exists']==True]

In [102]:
df2 = df_exists

In [107]:
ActualPreprocessedWithClass['exists'].value_counts()

exists
False    9925
True     7071
Name: count, dtype: int64

In [115]:
df2_common = df2[df2.index.isin(df1['Unnamed: 0'])]

In [112]:
common_indices['vid_name'].value_counts()

vid_name
#NAME?               64
j4gvbjifw14_00074     1
mGbuP7nT2ck_00158     1
mGbuP7nT2ck_00157     1
mGbuP7nT2ck_00156     1
                     ..
vlfy4cny75s_00109     1
vlfy4cny75s_00108     1
vlfy4cny75s_00107     1
vlfy4cny75s_00106     1
ovWCmIMMkRI_00052     1
Name: count, Length: 7007, dtype: int64

In [108]:
ActualPreprocessedWithClass[ActualPreprocessedWithClass['exists']==True]

       Unnamed: 0           vid_name  label  start_frame  end_frame  exists
3               3  3qq031609lA_00002      0            0        123    True
4               4  3qq031609lA_00004      0            0        102    True
5               5  5V-dKBtmKLI_00018      0            0         55    True
7               7  5V-dKBtmKLI_00085      0            0         80    True
8               8  5V-dKBtmKLI_00086      0            0         89    True
...           ...                ...    ...          ...        ...     ...
16991       16992  mGRum47TLX0_00040     47            0         56    True
16992       16993  mGRum47TLX0_00044     47            0        112    True
16993       16994  ovWCmIMMkRI_00050     47            0        108    True
16994       16995  ovWCmIMMkRI_00051     47            0        125    True
16995       16996  ovWCmIMMkRI_00052     47            0         91    True

[7071 rows x 6 columns]

In [114]:
df2

                vid_name  label  start_frame  end_frame  exists
0      -mmq0PT-u8k_00155      0            0         48    True
3      3qq031609lA_00002      0            0        123    True
4      3qq031609lA_00004      0            0        102    True
5      5V-dKBtmKLI_00018      0            0         55    True
7      5V-dKBtmKLI_00085      0            0         80    True
...                  ...    ...          ...        ...     ...
16992  mGRum47TLX0_00040     47            0         56    True
16993  mGRum47TLX0_00044     47            0        112    True
16994  ovWCmIMMkRI_00050     47            0        108    True
16995  ovWCmIMMkRI_00051     47            0        125    True
16996  ovWCmIMMkRI_00052     47            0         91    True

[7547 rows x 5 columns]

In [122]:
df2_common.to_csv('df_exists1.csv')

In [123]:
df2_common

                vid_name  label  start_frame  end_frame  exists
3      3qq031609lA_00002      0            0        123    True
4      3qq031609lA_00004      0            0        102    True
5      5V-dKBtmKLI_00018      0            0         55    True
7      5V-dKBtmKLI_00085      0            0         80    True
8      5V-dKBtmKLI_00086      0            0         89    True
...                  ...    ...          ...        ...     ...
16992  mGRum47TLX0_00040     47            0         56    True
16993  mGRum47TLX0_00044     47            0        112    True
16994  ovWCmIMMkRI_00050     47            0        108    True
16995  ovWCmIMMkRI_00051     47            0        125    True
16996  ovWCmIMMkRI_00052     47            0         91    True

[7070 rows x 5 columns]